version: '3'
services:

  ### Nginx container #########################################

  nginx:
      image: nginx:alpine
      container_name: nginx
      ports:
        - "${HTTP_PORT}:80"
        - "${HTTPS_PORT}:443"
        - "8080:8080"
        - "8888:8888"
        - "7777:7777"
      volumes:
        - ${PROJECT_FOLDER}:/etc/nginx/html/:rw
        - ./work/components/nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./work/components/nginx/config/conf.d:/etc/nginx/conf.d:ro
        - ./work/components/nginx/log:/var/log/nginx:rw
      restart: always
      privileged: true
      networks:
        - net-php
        - net-php7.3


  ### PHP 7.3 #########################################

  php7.3:
      build:
        context: ./build/php7.3
        args:
          TIME_ZONE: ${GLOBAL_TIME_ZONE}
          CHANGE_SOURCE: ${GLOBAL_CHANGE_SOURCE}
      container_name: php7.3
      volumes:
        - ${PROJECT_FOLDER}:/etc/nginx/html:rw
        - ./work/components/php/config7.3/php.ini:/usr/local/etc/php/php.ini:ro
        - ./work/components/php/config7.3/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:rw
        - ./work/components/php/log7.3:/var/log:rw
      restart: always
      privileged: true
      networks:
        - net-php7.3
        - net-mysql
        - net-redis

  ### PHP container #########################################

  php:
      build:
        context: ./build/php
        args:
          TIME_ZONE: ${GLOBAL_TIME_ZONE}
          CHANGE_SOURCE: ${GLOBAL_CHANGE_SOURCE}
      container_name: php7.4
      volumes:
        - ${PROJECT_FOLDER}:/etc/nginx/html:rw
        - ./work/components/php/config/php.ini:/usr/local/etc/php/php.ini:ro
        - ./work/components/php/config/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:rw
        - ./work/components/php/config/supervisord.conf:/etc/supervisor/supervisord.conf:rw  
        - ./work/components/php/log:/var/log:rw
      restart: always
      privileged: true
      networks:
        - net-php
        - net-mysql
        - net-redis

  ### Mysql container #########################################

  mysql:
      image: mysql:5.7
      container_name: msyql
      ports:
        - "${MYSQL_PORT}:3306"
      volumes:
        - ./work/components/mysql/data:/var/lib/mysql:rw
        - ./work/components/mysql/config/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
        - ./work/components/mysql/log:/var/log/mysql:rw
      restart: always
      privileged: true
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      networks:
        - net-mysql

  ### Redis container #########################################

  redis:
      image: redis:latest
      container_name: redis
      ports:
        - "${REDIS_PORT}:6379"
      volumes:
        - ./work/components/redis/config/redis.conf:/usr/local/etc/redis/redis.conf:ro
        - ./work/components/redis/log/redis.log:/var/log/redis/redis.log:rw
      restart: always
      privileged: true
      networks:
        - net-redis


networks:
  net-php7.3:
  net-php:
  net-mysql:
  net-redis:
